export const deptFaculty = [
  {
    image: "/assets/home/5.jpg",
    name: "Engr. Abdur Rehman Fasihi",
    qual: "B.E. Mechanical - (NED), M.Ed - (AKU)",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam, labore expedita. Excepturi quaerat nihil ad cum! Similique iusto quos soluta aliquid sequi vero, numquam exercitationem eligendi ut accusamus, maiores necessitatibus veniam esse. Sequi saepe quisquam, consectetur delectus excepturi unde sapiente!",
    dept: "Chemistry",
  },
  {
    image: "/assets/home/2.jpg",
    name: "Sir Jawwad Ahmed",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Physics",
  },
  {
    image: "/assets/home/2.jpg",
    name: "Sir Mudassir",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Physics",
  },
  {
    image: "/assets/home/4.jpg",
    name: "Sir Hassan",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Physics",
  },
  {
    image: "/assets/home/5.jpg",
    name: "Sir Zishad",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Chemistry",
  },
  {
    image: "/assets/home/5.jpg",
    name: "Sir Zishad",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Chemistry",
  },
  {
    image: "/assets/home/3.jpg",
    name: "Sir Zishad",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Chemistry",
  },
  {
    image: "/assets/home/5.jpg",
    name: "Sir Saleem",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Urdu",
  },
  {
    image: "/assets/home/5.jpg",
    name: "Sir Saleem",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Urdu",
  },
  {
    image: "/assets/home/5.jpg",
    name: "Sir Saleem",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Urdu",
  },
  {
    image: "/assets/home/5.jpg",
    name: "Sir Akram",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Mathematics",
  },
  {
    image: "/assets/home/5.jpg",
    name: "Sir Akram",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Mathematics",
  },
  {
    image: "/assets/home/5.jpg",
    name: "Sir Akram",
    qual: "Ph. D. Telecomm. (IU), M. S. Telecomm. (UIT), B. S. Electronics (SSUET)",
    desc:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio fuga optio mollitia exercitationem sapiente iusto consequatur sunt expedita numquam perferendis neque officia fugiat, laudantium ex enim nisi, cum eum pariatur minus excepturi eos nobis? Dolores tenetur totam expedita quia fugiat.",
    dept: "Mathematics",
  },
];
